version: "3"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch
    ports: 
      - "9300:9300"
      - "9200:9200"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"